name: apna_media_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  razorpay_flutter: ^1.3.7
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  video_player: ^2.8.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/apna_logo.png

# ðŸ”¥ APP ICON CONFIG
flutter_icons:
  android: true
  ios: true
  image_path: "assets/apna_logo.png"
  remove_alpha_ios: true

# ðŸ”¥ SPLASH SCREEN CONFIG
flutter_native_splash:
  color: "#ffffff"
  image: assets/apna_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center